export const REQUEST_DATA = "REQUEST_DATA";
export const REQUEST_DATA_SUCCESS = "REQUEST_DATA_SUCCESS";

export const FETCH_CITIES_ERROR = 'FETCH_CITIES_ERROR'
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS'
export const FETCH_CITIES_PENDING = 'FETCH_CITIES_PENDING'